from fpdf import FPDF


def sanitize(text: str) -> str:
    return text.encode("latin-1", errors="ignore").decode("latin-1")


def generate_interview_report(history: list, feedback: str) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 12, sanitize("Interview Report"), ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 8, sanitize("Generated by AskOne - AI Resume Interviewer"), ln=True, align="C")
    pdf.ln(6)

    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, sanitize("Interview Q&A"), ln=True)
    pdf.ln(2)

    for i, item in enumerate(history, start=1):
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(60, 90, 200)
        pdf.multi_cell(0, 7, sanitize(f"Q{i}: {item['question']}"))
        pdf.ln(1)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(40, 40, 40)
        answer = item["answer"].strip() if item["answer"].strip() else "No answer provided."
        pdf.multi_cell(0, 6, sanitize(answer))
        pdf.ln(5)

    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, sanitize("AI Feedback & Suggestions"), ln=True)
    pdf.ln(2)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(40, 40, 40)
    pdf.multi_cell(0, 6, sanitize(feedback))

    return bytes(pdf.output())